const AlphabetPosition = require('./solution');

const solution = new AlphabetPosition();
const text = " j!}/-?:";
const result = solution.alphabetPosition(text);
console.log(result);

console.log(solution.alphabetPosition(" j!}/-?:"));
console.log(solution.alphabetPosition("?)_b/,q("));
console.log(solution.alphabetPosition("(01:7co["));
console.log(solution.alphabetPosition("(pecthep"));
console.log(solution.alphabetPosition(")hy8:yv#"));
console.log(solution.alphabetPosition("}!g/$6h "));
console.log(solution.alphabetPosition("*.!@2%!("));
console.log(solution.alphabetPosition("/|2)<+$_"));
console.log(solution.alphabetPosition("/x9y62/z"));
console.log(solution.alphabetPosition("&?u7&@_h"));
console.log(solution.alphabetPosition("#rjf26wx"));
console.log(solution.alphabetPosition("%v0i#$1f"));
console.log(solution.alphabetPosition("^n%7_28b"));
console.log(solution.alphabetPosition("<csvc5b6"));
console.log(solution.alphabetPosition(">4@[{7+x"));
console.log(solution.alphabetPosition("$)^py>]v"));
console.log(solution.alphabetPosition("$^}[i%4x"));
console.log(solution.alphabetPosition("2!tw#^%="));
console.log(solution.alphabetPosition("2%s,lq;3"));
console.log(solution.alphabetPosition("21w;jo{4"));
console.log(solution.alphabetPosition("4.<esrvs"));
console.log(solution.alphabetPosition("4+$!.rey"));
console.log(solution.alphabetPosition("413x)!g]"));
console.log(solution.alphabetPosition("653/7%7+"));
console.log(solution.alphabetPosition("7f5f#z0&"));
console.log(solution.alphabetPosition("9?gwsh%<"));
console.log(solution.alphabetPosition("d))<bqax"));
console.log(solution.alphabetPosition("e[!o!:&r"));
console.log(solution.alphabetPosition("e936{oq0"));
console.log(solution.alphabetPosition("et$r!4?@"));
console.log(solution.alphabetPosition("gwfz96#<"));
console.log(solution.alphabetPosition("h5_}z{%>"));
console.log(solution.alphabetPosition("k;ur2   "));
console.log(solution.alphabetPosition("k.a,4}%|"));
console.log(solution.alphabetPosition("o-&u;/q/"));
console.log(solution.alphabetPosition("o9n&s-^@"));
console.log(solution.alphabetPosition("of8s@xuk"));
console.log(solution.alphabetPosition("pb$z ])j"));
console.log(solution.alphabetPosition("rvz:@&45"));
console.log(solution.alphabetPosition("t-^hnhl "));
console.log(solution.alphabetPosition("tdcxcaeb"));
console.log(solution.alphabetPosition("tg5a^b,."));
console.log(solution.alphabetPosition("um%ak4[w"));
console.log(solution.alphabetPosition("v2vs#;rz"));
console.log(solution.alphabetPosition("v8g-o#{>"));
console.log(solution.alphabetPosition("w}5#w_;}"));
console.log(solution.alphabetPosition("w$^(m[[/"));
console.log(solution.alphabetPosition("x?h?#c30"));
console.log(solution.alphabetPosition("x@@j[=f|"));