var alphabetPosition = require('./solution');


console.log(alphabetPosition(" j!}/-?:"));
console.log(alphabetPosition("?)_b/,q("));
console.log(alphabetPosition("(01:7co["));
console.log(alphabetPosition("(pecthep"));
console.log(alphabetPosition(")hy8:yv#"));
console.log(alphabetPosition("}!g/$6h "));
console.log(alphabetPosition("*.!@2%!("));
console.log(alphabetPosition("/|2)<+$_"));
console.log(alphabetPosition("/x9y62/z"));
console.log(alphabetPosition("&?u7&@_h"));
console.log(alphabetPosition("#rjf26wx"));
console.log(alphabetPosition("%v0i#$1f"));
console.log(alphabetPosition("^n%7_28b"));
console.log(alphabetPosition("<csvc5b6"));
console.log(alphabetPosition(">4@[{7+x"));
console.log(alphabetPosition("$)^py>]v"));
console.log(alphabetPosition("$^}[i%4x"));
console.log(alphabetPosition("2!tw#^%="));
console.log(alphabetPosition("2%s,lq;3"));
console.log(alphabetPosition("21w;jo{4"));
console.log(alphabetPosition("4.<esrvs"));
console.log(alphabetPosition("4+$!.rey"));
console.log(alphabetPosition("413x)!g]"));
console.log(alphabetPosition("653/7%7+"));
console.log(alphabetPosition("7f5f#z0&"));
console.log(alphabetPosition("9?gwsh%<"));
console.log(alphabetPosition("d))<bqax"));
console.log(alphabetPosition("e[!o!:&r"));
console.log(alphabetPosition("e936{oq0"));
console.log(alphabetPosition("et$r!4?@"));
console.log(alphabetPosition("gwfz96#<"));
console.log(alphabetPosition("h5_}z{%>"));
console.log(alphabetPosition("k;ur2   "));
console.log(alphabetPosition("k.a,4}%|"));
console.log(alphabetPosition("o-&u;/q/"));
console.log(alphabetPosition("o9n&s-^@"));
console.log(alphabetPosition("of8s@xuk"));
console.log(alphabetPosition("pb$z ])j"));
console.log(alphabetPosition("rvz:@&45"));
console.log(alphabetPosition("t-^hnhl "));
console.log(alphabetPosition("tdcxcaeb"));
console.log(alphabetPosition("tg5a^b,."));
console.log(alphabetPosition("um%ak4[w"));
console.log(alphabetPosition("v2vs#;rz"));
console.log(alphabetPosition("v8g-o#{>"));
console.log(alphabetPosition("w}5#w_;}"));
console.log(alphabetPosition("w$^(m[[/"));
console.log(alphabetPosition("x?h?#c30"));
console.log(alphabetPosition("x@@j[=f|"));